### ISSUE TITLE
RIP Bot (Enhancement)

### ISSUE THREAD

**Issue by ghost** [Jonarzz/DotaResponsesRedditBot#2]
In memory of the lost r/dota2smut bot on r/dota2, please add "Thus I invoke Masturbation" to the keyword "r/dota2smut" or when someone says "One of my favorites!"

He left a legacy, it's now your time to continue it.

Thank you.

**Comment by Jonarzz** [comment]
Done.

**Comment by FlorianWendelborn** [comment]
Don't forget to add `/r/dota2smut` too if you didn't already do it.

**Comment by Jonarzz** [comment]
I did, you can see it [here](https://github.com/Jonarzz/DotaResponsesRedditBot/blob/master/dota_responses_properties.py#L24).

7898588cfb314ba498571212227dc89b79563030

**Comment by FlorianWendelborn** [comment]
@Jonarzz Is it intended, that [this happens](https://www.reddit.com/r/DotA2/comments/4jc5io/meepo_girls_strike_back_as_phantom_lancer/d35mt26)? I was assuming it only happens when you link to the subreddit.

EDIT: According to the original request, this is intended. However, I'm not sure if this should stay.

**Comment by Jonarzz** [comment]
It has been like that since the feature was added and it seems to be okay with /r/DotA2 users.
