### ISSUE TITLE
Links are broken again

### ISSUE THREAD

**Issue by sanchitanand** [Jonarzz/DotaResponsesRedditBot#29]
Example:
https://www.reddit.com/r/DotA2/comments/atverq/gaben_clap/eh3ptrn/

The link provided:
https://d1u5p3l4wpay3k.cloudfront.net/dota2_gamepedia/5/51/Mir_ability_arrow_11.mp3

Actual link:
https://gamepedia.cursecdn.com/dota2_gamepedia/5/51/Mir_ability_arrow_11.mp3

**Comment by sanchitanand** [comment]
Also, this line in the parser causes it to not search many response files, since they are all named like 'HeroName/Responses'
https://github.com/Jonarzz/DotaResponsesRedditBot/blob/master/responses_wiki/dota_wiki_parser.py#L138 
`if isinstance(value, str) and '/' not in value:`

I would change it to 
`if isinstance(value, str):`

**Comment by MePsyDuck** [comment]
I believe this is due to recent server migrations at gamepedia. 
I was supposed to be redoing the whole module but got stuck in work and study. I think that the original owner of the bot @Jonarzz is no longer actively monitoring the bot. Can you go ahead and open this issue in my [fork](https://github.com/MePsyDuck/DotaResponsesRedditBot) of this repo? I'll start this project again and hopefully, finish it in this month<sup>Valve Time<sup>TM</sup></sup>Also, you're most welcome if you wish to contribute to rebuilding the bot.

**Comment by MePsyDuck** [comment]
Fixed with https://github.com/Jonarzz/DotaResponsesRedditBot/pull/31
